"""exercise execution type longer

Revision ID: 08c48a9cf13b
Revises: 48ce06e59226
Create Date: 2023-02-09 12:11:16.026879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c48a9cf13b'
down_revision = '48ce06e59226'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
