"""added Therapy and User inheritance

Revision ID: 1fa4db46f653
Revises: 8f61d38bf284
Create Date: 2023-01-31 09:55:17.057442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1fa4db46f653'
down_revision = '8f61d38bf284'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('social_security_number', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('therapists',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('clinic', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('therapies',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('patient_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('therapist_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapies_id'), 'therapies', ['id'], unique=False)
    op.add_column('trainings', sa.Column('patient_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('trainings_user_id_fkey', 'trainings', type_='foreignkey')
    op.create_foreign_key(None, 'trainings', 'patients', ['patient_id'], ['id'])
    op.drop_column('trainings', 'user_id')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'type')
    op.drop_column('users', 'is_admin')
    op.add_column('trainings', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trainings', type_='foreignkey')
    op.create_foreign_key('trainings_user_id_fkey', 'trainings', 'users', ['user_id'], ['id'])
    op.drop_column('trainings', 'patient_id')
    op.drop_index(op.f('ix_therapies_id'), table_name='therapies')
    op.drop_table('therapies')
    op.drop_table('therapists')
    op.drop_table('patients')
    # ### end Alembic commands ###
