"""exercise execution fix

Revision ID: 343a2762e549
Revises: d6950559358a
Create Date: 2023-02-09 09:17:46.129027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343a2762e549'
down_revision = 'd6950559358a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
