"""Removed ExerciseDuration polymorph

Revision ID: 48ce06e59226
Revises: 343a2762e549
Create Date: 2023-02-09 12:07:59.110675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ce06e59226'
down_revision = '343a2762e549'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
