"""Fixed TrainingPlanExercise

Revision ID: de60d207fbf1
Revises: 08c48a9cf13b
Create Date: 2023-02-09 12:32:40.395773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de60d207fbf1'
down_revision = '08c48a9cf13b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_plan_exercise', sa.Column('exercise_interval_id', sa.UUID(), nullable=True))
    op.drop_constraint('training_plan_exercise_interval_id_fkey', 'training_plan_exercise', type_='foreignkey')
    op.create_foreign_key(None, 'training_plan_exercise', 'exercise_interval', ['exercise_interval_id'], ['id'])
    op.drop_column('training_plan_exercise', 'interval_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_plan_exercise', sa.Column('interval_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'training_plan_exercise', type_='foreignkey')
    op.create_foreign_key('training_plan_exercise_interval_id_fkey', 'training_plan_exercise', 'exercise_interval', ['interval_id'], ['id'])
    op.drop_column('training_plan_exercise', 'exercise_interval_id')
    # ### end Alembic commands ###
