"""Added Exercise second

Revision ID: f656fc790689
Revises: 570c14e3398b
Create Date: 2023-01-04 10:03:21.240779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f656fc790689'
down_revision = '570c14e3398b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('description', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('image_path', sa.String(length=256), nullable=True))
    op.add_column('exercises', sa.Column('difficulty', sa.SmallInteger(), nullable=True))
    op.alter_column('exercises', 'name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.add_column('users', sa.Column('lastname', sa.String(length=256), nullable=True))
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('users', 'lastname')
    op.alter_column('exercises', 'name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.drop_column('exercises', 'difficulty')
    op.drop_column('exercises', 'image_path')
    op.drop_column('exercises', 'description')
    # ### end Alembic commands ###
