version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    depends_on:
      - db
  api:
    build: ./api
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - db
    volumes:
      - ./api:/code
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
  webapp:
    build: ./webapp
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - api
    volumes:
      - './webapp:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  db:
    driver: local
  files:
    driver: local
